### PR TITLE
Update DisplayControl

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description
- Reworked DisplayControl so no hard coded  ScreenWidth & ScreenHeight
- Made completely static so no need to create instance of it.
- Added option parameter to get the FullScreen bitmap which it automatically allocates (optional)
- Tidied up comments
- If ChangeOrientation called will will dispose of current bitmap so new one can be allocated with new dimensions. 

## Motivation and Context
Fix issues

## How Has This Been Tested?
Tested with current samples. Mainly Primitive but changes needed to test other samples.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AdrianSoundy** [comment]
@josesimoes Can you have a look why thus is failing. Something about code signing. Have things been changed ?

**Review by josesimoes — APPROVED** [review]
LGTM

**Comment by josesimoes** [comment]
@AdrianSoundy please check the complains from SonarCloud.

**Comment by AdrianSoundy** [comment]
@josesimoes , Sonar has no issues now as I had already fixed them but it still says failed. I think it because build fails on code signing step. Can I just merge ?

**Comment by josesimoes** [comment]
> @josesimoes , Sonar has no issues now as I had already fixed them but it still says failed. I think it because build fails on code signing step. Can I just merge ?

SonarCloud was complaining about code coverage. I've changed the setting on the project configuration now.
As for the code signing. I'll add the missing files and it should be OK.

**Pull request merged**
